{% set version = "0.9.0" %}

package:
  name: torchdata
  version: {{ version }}

source:
  url: https://github.com/pytorch/data/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b547bbe848ad813cc5365fe0bb02051150bec6c7c4ee7bffd6b6d3d7bdeddd75

build:
  number: 0
  # no pytorch on windows in conda-forge, see
  # https://github.com/conda-forge/pytorch-cpu-feedstock/issues/32
  skip: true  # [win]
  ignore_run_exports_from:
    # CMake really wants to find it, but we don't need it
    - zlib
  script:
    - export BUILD_S3=TRUE
    - export CMAKE_GENERATOR="Ninja"
    - export USE_SYSTEM_LIBS=TRUE
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - pytorch                                # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
  host:
    - pip
    - setuptools
    - python
    - pybind11
    - aws-sdk-cpp
    - pytorch
    - zlib
  run:
    - python
    - requests
    - urllib3 >=1.25
    - pytorch

test:
  imports:
    - torchdata
  requires:
    - pip
    - pytest
    - pytest-xdist
    - adlfs
    - awscli
    - cryptography
    - datasets
    - expecttest
    - fsspec
    - numpy *
    - msal_extensions >=1.2
    - portalocker >=2.0.0
    - psutil
    - s3fs >=2023.12.2
  source_files:
    - test/
  commands:
    - pip check
    - cd test
    {% set tests_to_skip = "_not_a_real_test" %}
    # flaky tests
    {% set tests_to_skip = tests_to_skip + " or test_fsspec_memory_list" %}
    {% set tests_to_skip = tests_to_skip + " or test_elastic_training_dl1_backend_gloo" %}
    {% set tests_to_skip = tests_to_skip + " or test_elastic_training_dl2_backend_gloo" %}
    {% set tests_to_skip = tests_to_skip + " or test_ind_worker_queue" %}                   # [osx]
    # fails because fsspec is not available (AWS S3 stuff)
    {% set tests_to_skip = tests_to_skip + " or test_fsspec_io_iterdatapipe" %}
    {% set tests_to_skip = tests_to_skip + " or test_s3_io_iterdatapipe" %}
    # tend to fail due to Google Drive rate-limiting
    {% set tests_to_skip = tests_to_skip + " or test_gdrive_iterdatapipe" %}
    {% set tests_to_skip = tests_to_skip + " or test_online_iterdatapipe" %}
    # 20231124 - disable tests that might timeout after 6 hours
    # https://github.com/pytorch/data/blob/v0.7.1/test/dataloader2/test_mprs.py#L233
    {% set tests_to_skip = tests_to_skip + " or test_early_exit_ctx_" %}
    {% set tests_to_skip = tests_to_skip + " or test_reading_service_limit_dp1" %}
    # issue with deprecated module `datapipes` not being loaded lazily
    {% set tests_to_skip = tests_to_skip + " or (TestTorchDataLazyImport_shard3 and test_lazy_imports)" %}
    # failures on py313
    {% set tests_to_skip = tests_to_skip + " or TestStatefulDataLoaderIterable_shard0" %}
    # very long-running test (~5min)
    {% set tests_to_skip = tests_to_skip + " or test_shuffler_iterdatapipe" %}
    {% set tests_to_skip = tests_to_skip + " or test_iterable_style_dataset" %}             # [osx]
    # 19/26 tests that match this condition run >2min on osx
    {% set tests_to_skip = tests_to_skip + " or (test_state_dict.py and DataLoader)" %}     # [osx]
    # test_audio_examples uses an uninstalled local folder ("examples");
    # avoid test_text_examples due to cycle since torchtext depends on torchdata
    - pytest -n auto -v --ignore=test_audio_examples.py --ignore=test_text_examples.py -k "not ({{ tests_to_skip }})" --durations=50

about:
  home: https://github.com/pytorch/data
  summary: A PyTorch repo for data loading and utilities to be shared by the PyTorch domain libraries.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - weiji14
    - BastianZim
    - Tobias-Fischer
    - h-vetinari
