{% set version = "0.10.1" %}

package:
  name: torchdata
  version: {{ version }}

source:
  url: https://github.com/pytorch/data/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 42f977c6a4a890848ef50c4ce3e01beeec04cc921e3ccc71d941f97de209bbfb

build:
  number: 0
  ignore_run_exports_from:
    # CMake really wants to find it, but we don't need it
    - zlib
  script:
    - export BUILD_VERSION={{ version }}    # [unix]
    - set BUILD_VERSION={{ version }}       # [win]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
  host:
    - pip
    - setuptools
    - python
  run:
    - python
    - requests
    - urllib3 >=1.25
    - pytorch

test:
  imports:
    - torchdata
  requires:
    - pip
    - pytest
    - pytest-xdist
    - adlfs
    - awscli
    - cryptography
    - datasets
    - expecttest
    - fsspec
    - numpy *
    - msal_extensions >=1.2
    - parameterized
    - portalocker >=2.0.0
    - psutil
    - s3fs >=2023.12.2
  source_files:
    - test/
  commands:
    - pip check
    # ensure that the package metadata did not mangle in the git hash
    - test -f $SP_DIR/torchdata-{{ version }}.dist-info/METADATA                # [unix]
    - if not exist %SP_DIR%\torchdata-{{ version }}.dist-info\METADATA exit 1   # [win]
    - cd test
    {% set tests_to_skip = "_not_a_real_test" %}
    # flaky tests
    {% set tests_to_skip = tests_to_skip + " or test_large_sampler_indices" %}              # [osx]
    {% set tests_to_skip = tests_to_skip + " or (TestDataLoader and test_segfault)" %}      # [osx]
    {% set tests_to_skip = tests_to_skip + " or test_get_worker_info" %}                    # [osx or win]
    {% set tests_to_skip = tests_to_skip + " or test_ind_worker_queue" %}                   # [osx or win]
    {% set tests_to_skip = tests_to_skip + " or test_batch_sampler" %}                      # [win]
    {% set tests_to_skip = tests_to_skip + " or test_thread_dead_error" %}                  # [win]
    {% set tests_to_skip = tests_to_skip + " or (TestMap and test_in_order_process)" %}     # [win]
    # failures on py313
    {% set tests_to_skip = tests_to_skip + " or TestStatefulDataLoaderIterable_shard0" %}   # [py==313]
    # may hang or OOM on windows
    {% set tests_to_skip = tests_to_skip + " or test_distributed_dl1_backend_gloo" %}       # [win]
    {% set tests_to_skip = tests_to_skip + " or test_distributed_dl2_backend_gloo" %}       # [win]
    {% set tests_to_skip = tests_to_skip + " or test_tfrecord_loader_sequence_example" %}   # [win]
    # very long-running test (~5min)
    {% set tests_to_skip = tests_to_skip + " or test_shuffler_iterdatapipe" %}
    {% set tests_to_skip = tests_to_skip + " or test_iterable_style_dataset" %}             # [osx]
    # 19/26 tests that match this condition run >2min on osx/win
    {% set tests_to_skip = tests_to_skip + " or (test_state_dict.py and DataLoader)" %}     # [osx or win]
    # test_audio_examples uses an uninstalled local folder ("examples");
    # avoid test_text_examples due to cycle since torchtext depends on torchdata
    - pytest -n auto -v --ignore=test_audio_examples.py --ignore=test_text_examples.py -k "not ({{ tests_to_skip }})" --durations=50

about:
  home: https://github.com/pytorch/data
  summary: A PyTorch repo for data loading and utilities to be shared by the PyTorch domain libraries.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - weiji14
    - BastianZim
    - Tobias-Fischer
    - h-vetinari
