azure:
  free_disk_space: true
  settings_linux:
    swapfile_size: 10GiB
  settings_win:
    variables:
      CONDA_BLD_PATH: C:\\bld\\
      MINIFORGE_HOME: C:\\Miniforge
      SET_PAGEFILE: 'True'
bot:
  inspection: update-grayskull
  version_updates:
    exclude:
      # spurious tag that got deleted, but broke the bot permanently;
      # could also be fixed by https://github.com/regro/cf-graph-countyfair/pull/41
      - "1217"
build_platform:
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
test: native_and_emulated
